// <auto-generated />
namespace MyELearningProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migaddprop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migaddprop));
        
        string IMigrationMetadata.Id
        {
            get { return "202312041404147_mig-add-prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
